concurrency: 1
delay: 0
logfile: ./shoryuken.log
pidfile: ./shoryuken.pid
queues:
  - [<%= ENV['SQS_QUEUE'] %>, 1]
wait_time_seconds: 20
aws:
  access_key_id: <%= ENV['SQS_AWS_ACCESS_KEY'] %>
  region: <%= ENV['AWS_SQS_REGION'] %>
  secret_access_key:  <%= ENV['SQS_AWS_SECRET_KEY'] %>

